name: Deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run script
        run: ${{ secrets.MY_SECRET_SCRIPT }}
