name: Deploy
on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          SCRIPT: ${{ secrets.MY_SECRET_SCRIPT }}
      - name: Run script
        run: ${SCRIPT}
